version: '3'
services:
  virtual-biker:
    build: .
    environment:
      - TIMEOUT=5
      - DEPLOYMENT=production
      - REPORT_RESULTS=false
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: any